name: Generate Unity xref maps
on:
  schedule:
    # do once a week at midnight on Sunday
    - cron: '0 0 * * 0'
  workflow_dispatch:
permissions:
  actions: read
  pages: write
  id-token: write
concurrency:
  group: unity-xref-maps
  cancel-in-progress: true
jobs:
  generate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - run: |
          dotnet tool update -g docfx
          ./generate-xref-maps.ps1
        shell: pwsh
      - uses: actions/upload-pages-artifact@v3
      - uses: actions/deploy-pages@v4
